POST http://127.0.0.1:4000/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 100,
  "tipo": "d",
  "descricao": "Compra de roupas"
}

---

GET http://127.0.0.1:4000/clientes/1/extrato